site_name: Andy's Notes

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: orange

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - toc


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Artificial Intelligence: 
      - Overview: index.md
      - Hardware:
          - Hardware: hardware.md
          - Memory Hierarchy Design: memory.md
          - Parallel Computing: parallelism.md
          - Cache-Aware Matrix Multiplication & GPU Performance Analysis: cpu-vs-gpu-matrix.md
      - Software:
          - CUDA C/C++: cuda.md
      - Convolutional Neural Networks:
          - CNN Concepts: neural.md
          - 1-D CNN Examples: 1d_cnn.md
      - Nvidia's Jetson Nano: jetson.md
  - Automotive:
      - Overview: Automotive/pages/index.md
      - Electrical/Electronic Architecture: Automotive/pages/architecture.md
      - External Sensors and Signals: Automotive/pages/sensorsSignals.md
      - Protocols:
        - CAN: Protocols/pages/can.md
      - Hardware: 
        - Power Distribution Module: Automotive/pages/pdm.md
  - Cyber Security:
      - Overview: Cybersecurity/pages/index.md
  - Digital Systems Design:
      - Overview: DSD/index.md
      - Verilog: DSD/verilog.md
      - Logic Design: DSD/logicDesign.md
      - Simulations: DSD/simulations.md
      - Examples: DSD/applications.md
  - Electronics:
      - Overview: electronics/pages/index.md
      - Measuring Equipment: electronics/pages/equipment.md
      - Operational Amplifiers: electronics/pages/opamp.md
      - Analog to Digital Converter: electronics/pages/adc.md
  - Physics:
      - Overview: Physics/pages/index.md
      - Quanta and Fields: 
        - Wave Function: Physics/pages/waveFunction.md
        - Measurement: Physics/pages/measurement.md
        - Entanglement: Physics/pages/entanglement.md
        - Fields: Physics/pages/fields.md
  - Protocols and Interfaces:
    - Overview: Protocols/pages/index.md
    - CAN: Protocols/pages/can.md
  - Senior Design:
    - Overview: senior_design/pages/index.md
  - Signals:
      - Overview: Signals/pages/index.md
      - Digital Signal Processing: Signals/pages/introDsp.md
      - FCC Electromagnetic Spectrum: Signals/pages/spectrum.md
  - Software:
      - Overview: Software/pages/index.md
      - Software Development Flow: Software/pages/developmentProcess.md
      - C Programming Language: Software/pages/c.md

extra:
  footer:
    text: "© 2025 Andy's Notes. All rights reserved."
